// <auto-generated />
namespace Soft_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addCategoryID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCategoryID));
        
        string IMigrationMetadata.Id
        {
            get { return "202003270040280_addCategoryID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
